### ISSUE TITLE
Where is the operation of Voting?

### ISSUE THREAD

**Issue by CSer-Tang-hao** [FingerRec/RHE#1]
This is an interesting work, but I can't find the operation of voting in the tedious code.  This operation is whether used in the training and testing stage?

**Comment by FingerRec** [comment]
Hi,
Sorry for the late reply!
"Voting" is accurately implemented via "_average_" operation over branches.
That is, the model learn various weights for different samples.
In fact, depends on temporal abstraction.
During training, we average all branches while all but the first in test.
